# Generated by Django 5.2.1 on 2025-05-31 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Name (Arabic)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabic)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('icon', models.CharField(default='fas fa-microchip', max_length=50, verbose_name='Icon Class')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='ElectronicPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name_ar', models.CharField(max_length=200, verbose_name='Name (Arabic)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('part_number', models.CharField(max_length=100, unique=True, verbose_name='Part Number')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabic)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Total Quantity')),
                ('available_quantity', models.PositiveIntegerField(default=0, verbose_name='Available Quantity')),
                ('borrowed_quantity', models.PositiveIntegerField(default=0, verbose_name='Borrowed Quantity')),
                ('damaged_quantity', models.PositiveIntegerField(default=0, verbose_name='Damaged Quantity')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Brand')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('specifications', models.TextField(blank=True, verbose_name='Specifications')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Storage Location')),
                ('max_borrow_days', models.PositiveIntegerField(default=7, verbose_name='Max Borrow Days')),
                ('max_quantity_per_user', models.PositiveIntegerField(default=1, verbose_name='Max Quantity Per User')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Requires Approval')),
                ('image', models.ImageField(blank=True, null=True, upload_to='parts/', verbose_name='Image')),
                ('datasheet', models.FileField(blank=True, null=True, upload_to='datasheets/', verbose_name='Datasheet')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Electronic Part',
                'verbose_name_plural': 'Electronic Parts',
                'ordering': ['name_ar'],
            },
        ),
    ]
