# Generated by Django 5.2.1 on 2025-06-02 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='electronicpart',
            name='borrowed_quantity',
        ),
        migrations.RemoveField(
            model_name='electronicpart',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='electronicpart',
            name='damaged_quantity',
        ),
        migrations.RemoveField(
            model_name='electronicpart',
            name='datasheet',
        ),
        migrations.RemoveField(
            model_name='electronicpart',
            name='max_borrow_days',
        ),
        migrations.RemoveField(
            model_name='electronicpart',
            name='max_quantity_per_user',
        ),
        migrations.RemoveField(
            model_name='electronicpart',
            name='requires_approval',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='electronicpart',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_parts', to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='electronicpart',
            name='condition',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged'), ('out_of_order', 'Out of Order')], default='excellent', max_length=20, verbose_name='Condition'),
        ),
        migrations.AddField(
            model_name='electronicpart',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='electronicpart',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Minimum Stock'),
        ),
        migrations.AddField(
            model_name='electronicpart',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='electronicpart',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase Date'),
        ),
        migrations.AddField(
            model_name='electronicpart',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Purchase Price'),
        ),
        migrations.AddField(
            model_name='electronicpart',
            name='shelf_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Shelf Number'),
        ),
        migrations.AddField(
            model_name='electronicpart',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('maintenance', 'Under Maintenance'), ('discontinued', 'Discontinued')], default='available', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='electronicpart',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='Arabic Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='electronicpart',
            name='available_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Available Quantity'),
        ),
        migrations.AlterField(
            model_name='electronicpart',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='inventory.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='electronicpart',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='Arabic Description'),
        ),
        migrations.AlterField(
            model_name='electronicpart',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='English Description'),
        ),
        migrations.AlterField(
            model_name='electronicpart',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='electronicpart',
            name='name_ar',
            field=models.CharField(max_length=200, verbose_name='Arabic Name'),
        ),
        migrations.AlterField(
            model_name='electronicpart',
            name='name_en',
            field=models.CharField(max_length=200, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='electronicpart',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, verbose_name='Technical Specifications'),
        ),
        migrations.AlterField(
            model_name='electronicpart',
            name='total_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Total Quantity'),
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('transaction_type', models.CharField(choices=[('add', 'Added to Inventory'), ('remove', 'Removed from Inventory'), ('borrow', 'Borrowed'), ('return', 'Returned'), ('damaged', 'Marked as Damaged'), ('repair', 'Repaired'), ('adjustment', 'Inventory Adjustment')], max_length=20, verbose_name='Transaction Type')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('previous_quantity', models.PositiveIntegerField(verbose_name='Previous Quantity')),
                ('new_quantity', models.PositiveIntegerField(verbose_name='New Quantity')),
                ('reason', models.TextField(blank=True, verbose_name='Reason/Notes')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='Reference ID')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.electronicpart')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Specification Name')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unit')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='inventory.electronicpart')),
            ],
            options={
                'verbose_name': 'Part Specification',
                'verbose_name_plural': 'Part Specifications',
                'unique_together': {('part', 'name')},
            },
        ),
    ]
