# Generated by Django 5.2.1 on 2025-05-31 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Request Date')),
                ('purpose', models.TextField(verbose_name='Purpose of Use')),
                ('expected_return_date', models.DateField(verbose_name='Expected Return Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('borrowed', 'Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('damaged', 'Damaged')], default='draft', max_length=20, verbose_name='Status')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('borrowed_date', models.DateTimeField(blank=True, null=True, verbose_name='Borrowed Date')),
                ('actual_return_date', models.DateTimeField(blank=True, null=True, verbose_name='Actual Return Date')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('student_notes', models.TextField(blank=True, verbose_name='Student Notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Borrow Request',
                'verbose_name_plural': 'Borrow Requests',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('condition_borrowed', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair')], default='excellent', max_length=20, verbose_name='Condition When Borrowed')),
                ('condition_returned', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged')], max_length=20, verbose_name='Condition When Returned')),
                ('damage_description', models.TextField(blank=True, verbose_name='Damage Description')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.electronicpart')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='borrowing.borrowrequest')),
            ],
            options={
                'verbose_name': 'Borrow Record',
                'verbose_name_plural': 'Borrow Records',
            },
        ),
    ]
