# Generated by Django 5.2.1 on 2025-06-02 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='part',
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='inventory_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.electronicpart', verbose_name='Inventory Part'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='part_description',
            field=models.TextField(blank=True, verbose_name='Part Description'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='part_name',
            field=models.CharField(default=1, max_length=200, verbose_name='Part Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='condition_borrowed',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged')], default='excellent', max_length=20, verbose_name='Condition When Borrowed'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='borrowing.borrowrequest', verbose_name='Borrow Request'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('borrowed', 'Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('damaged', 'Damaged')], default='submitted', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
    ]
