# Generated by Django 5.2.1 on 2025-06-02 04:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_remove_borrowrecord_part_borrowrecord_inventory_part_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('action', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('borrowed', 'Borrowed'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('reminder_sent', 'Reminder Sent'), ('marked_overdue', 'Marked Overdue'), ('note_added', 'Note Added')], max_length=20, verbose_name='Action')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Borrow Request History',
                'verbose_name_plural': 'Borrow Request Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Part Number'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='replacement_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Replacement Cost'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='serial_numbers',
            field=models.JSONField(blank=True, default=list, help_text='List of serial numbers for tracked items', verbose_name='Serial Numbers'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit for damage/loss tracking', max_digits=10, null=True, verbose_name='Unit Cost'),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional: Circuit diagram, project description, etc.', upload_to='borrow_requests/', verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='overdue_notified',
            field=models.BooleanField(default=False, verbose_name='Overdue Notification Sent'),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Reminder Sent'),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='Urgency'),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='condition_borrowed',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged'), ('missing', 'Missing')], default='excellent', max_length=20, verbose_name='Condition When Borrowed'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='condition_returned',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged'), ('missing', 'Missing')], max_length=20, verbose_name='Condition When Returned'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('borrowed', 'Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('damaged', 'Damaged'), ('cancelled', 'Cancelled')], default='submitted', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterUniqueTogether(
            name='borrowrecord',
            unique_together={('request', 'part_name', 'part_number')},
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['status', 'request_date'], name='borrowing_b_status_132b16_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['student', 'status'], name='borrowing_b_student_4d7144_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrequest',
            index=models.Index(fields=['expected_return_date'], name='borrowing_b_expecte_5ff5f4_idx'),
        ),
        migrations.AddField(
            model_name='borrowrequesthistory',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowrequesthistory',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='borrowing.borrowrequest'),
        ),
    ]
