# Generated by Django 5.2.1 on 2025-05-31 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Administrator')], default='student', max_length=20, verbose_name='User Type')),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Student ID')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone Number')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('is_active_borrower', models.BooleanField(default=True, verbose_name='Can Borrow')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
